config/routes.rb
Rails.application.routes.draw do
	resources :searchs
	resources :cases
	root'cases#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
	 
  
  self.abstract_class = true
end

app/models/case.rb
class Case < ApplicationRecord
	 #extend FriendlyId
	#friendly_id :name, use: :slugged
	validates :title, uniqueness: true
	validates :content, uniqueness: true

	self.per_page = 15


	extend FriendlyId
	friendly_id :slug_candidates, use: :slugged


	def slug_candidates
      [
        :title,
        [:title, :created_at]
      ]
    end

end

app/models/search.rb
class Search < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cases_controller.rb
class CasesController < ApplicationController
  before_action :set_case, only: [:show, :update, :edit]

  def index
    @case = Case.paginate(:page => params[:page])
  end

  def show
    @related_cases = Case.where.not(id: @case.id).order("RANDOM()").limit(3)
  end

  def edit
  end


  def update
    respond_to do |format|
      if @case.update(case_params)
        format.html { redirect_to @case, notice: 'Case was successfully updated.' }
        format.json { render :show, status: :ok, location: @case }
      else
        format.html { render :edit }
        format.json { render json: @case.errors, status: :unprocessable_entity }
      end
    end
  end

  

  private

    def set_case
      @case = Case.friendly.find(params[:id])
      # .find(params[:id])
    end


    def case_params
      params.require(:case).permit(:title, :content)
    end
end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
  def show
  	@search = Search.find(params[:id])
  	@cases = Case.where(title: @search.keyword).order("created_at DESC")
  end

  def create

  	@search = Search.new(set_params)

  	if @search.save
  		render :show
  	end

  end

  private

  	def set_params
  		params.require(:search).permit(:keyword)
  	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cases_helper.rb
module CasesHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/views/cases/_form.html.erb
<%= form_with @case do |form| %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cases/edit.html.erb
<div class="container">

<h1>Editing Case</h1>


<%= form_for @case do |form| %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>



<%= link_to 'Show', @case %> |
<%= link_to 'Back', cases_path %>

</div>

app/views/cases/index.html.erb
<div class="container">
	<div class="lists_display">
		<% @case.each do |law| %>
			<a href="<%= case_path(law) %>">
				<div class="list_view">
				 	<h4>
				 		<% if law.title? %>
					 		<%= law.title %>
			 			<% else %>
			 			<span id="no_title_yellow">
			 				No Title As off <%= Date.today %>
			 			</span>
				 		<% end %>
			 		</h4>
				 	<p id="simplecontent">
				 		<% if law.content? %>
				 			<%= truncate(law.content, length: 200) %>
			 			<% else %>
			 				<span id="no_content_red">
				 				No content as of <%= Date.today %>
				 			</span>
				 		<% end %>
				 			
			 		</p>	
				</div>
			</a>		
		  
		<% end %>
		<%= will_paginate @case , :page_links => false %>
	</div>

</div>

app/views/cases/new.html.erb
<h1>New Case</h1>

<%= render 'form', case: @case %>

<%= link_to 'Back', cases_path %>

app/views/cases/show.html.erb
<div class="container">
	<div class="small_container">

		<div class="aSpace">
			
		</div>

		<div>
		  <strong>Case Name</strong> <br>
		  <h1 id="title"><%= @case.title %></h1>
		</div>

		<% if @case.content? %>
		<div>

			<strong>Facts and Judgment </strong>
			<br>
			
			<div id="content">
			  <%= @case.content %>
			</div>

		</div>
		<% end %>

		<hr>

		<strong id="birth_mark">Similer Cases</strong>


		<div class="related_cases">
			<% @related_cases.each do |c| %>
				<a href="<%= case_path(c)%>">
					<div class="item">
						<h5><%= c.title %></h5>
						<%= truncate(c.content, length: 100) %>
					</div>
				</a>
			<% end %>


		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Law</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.7.2/angular.min.js"></script>
    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>

  </head>

  <body ng-app="lawApp">
    <%= render 'navs/navbar' %>
    <%= yield %>

  </body>
</html>

app/views/navs/_navbar.html.erb
<nav class="top-white-nav" ng-controller="searchCtrl">
  <div class="container">

    <div class="row">
      <div class="col alight_left">
        <a href="<%= root_path %>">
          <label class="logo">Lawprofessor</label>
        </a>
      </div>
      <div class="col">
        <div id="search_bar">
          <input type="search" placeholder="Search ..." ng-model="keyword" id="searchBox" onfocus="showSearchResults()">
          <div class="searchResults disable" id="searchResults">
            <ul>
              <li ng-repeat="law in cases | filter: keyword">
                <h5>
                  <a ng-href="{{law.case_link}}">
                    {{law.case_name}}
                    <hr>
                  </a>
                </h5>
              </li>
            </ul>
          </div>
          <div id="counter_event" onClick="counterAct()" class="disable">
          </div>
        </div>
      </div>
      <div class="col alight_right">
        <button id="submit_report">
          Contact Us
        </button>
      </div>
    </div>
    <hr>

  </div>

</nav>



<!-- <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%= root_path%>">Law</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="<%= cases_path %>">Cases</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>

    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav> -->

app/views/searchs/new.html.erb
<h1>Searchs#new</h1>
<p>Find me in app/views/searchs/new.html.erb</p>

app/views/searchs/show.html.erb
<div class="container">
	<p> Results for Keyword: <%= @search.keyword %> </p>
	<%= @cases.count %>

</div>